version: '3.8'
services:
    redis:
        image: redis:alpine
        container_name: redis

    db:
        image: postgres:alpine
        container_name: database
        environment:
            - POSTGRES_PASSWORD=password
    
    app:
        build: .
        container_name: threader
        environment:
            - DATABASE_URL=postgres://postgres:password@db:5432/threadxer
            - REDIS_URL=redis://redis:6379
        ports:
            - 5173:5173
            - 8080:8080
        depends_on:
            - redis
            - db